{"uuid": "189a7994-ca5a-4804-b528-0c29e029bfc3", "children": ["1364e099-5bc8-41ce-b2be-48953738de1a"], "befores": [{"name": "beginandend", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"C:\\python\\3.10\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python\\3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python\\3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\UIauto\\WebUIAutoTest-master\\TestCase\\conftest.py\", line 20, in beginToend\n    driver = webdriver.firefox()\n"}, "start": 1692770008460, "stop": 1692770008473}], "start": 1692770008460, "stop": 1692770008583}